version: "3.8"

networks:
  propertymanagement-network:

services:
  propertymanagementdotnetwebapi:
    container_name: propertymanagementdotnetwebapi
    image: ${DOCKER_REGISTRY-}propertymanagementdotnetwebapi
    build:
      context: PropertyManagementDotnetWebApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - propertymanagement-network
  frontend:
    container_name: frontend
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - propertymanagement-network
